"""Golden-replay: run the pipeline on a recorded raw CSV and assert
the corrected output matches the checked-in golden byte-for-byte.

For PR 1, the goldens are self-consistent (generated by the same pipeline
they're testing). This catches regressions but does not validate against
the legacy SciencePipeline — that is a PR 2 task.

Golden fixtures live in tests/test_pipeline/data/:
    normal_short_scan.raw.csv               — synthetic 50-frame raw input
    normal_short_scan.corrected.golden.csv  — pipeline's corrected output

Run regenerate_goldens.py (in the same directory) to refresh both files
when the pipeline algorithm changes intentionally.
"""

from __future__ import annotations

import csv
import pathlib

import numpy as np
import pytest
from dataclasses import dataclass

from omotion.pipeline.factory import default_pipeline
from omotion.pipeline.runner import ScanRunner
from omotion.pipeline.sources import CsvReplaySource
from omotion.pipeline.sinks import CsvSink, ScanMetadata, _NORMAL_HEADERS
from omotion.pipeline.pedestal import SensorPedestals


HERE = pathlib.Path(__file__).parent / "data"

_PEDESTAL = 64.0
_DARK_INTERVAL = 20   # must match regenerate_goldens.py


@dataclass
class _TrivialCal:
    c_min: np.ndarray
    c_max: np.ndarray
    i_min: np.ndarray
    i_max: np.ndarray


def _trivial_calibration() -> _TrivialCal:
    return _TrivialCal(
        c_min=np.zeros((2, 8), dtype=np.float32),
        c_max=np.ones((2, 8), dtype=np.float32),
        i_min=np.zeros((2, 8), dtype=np.float32),
        i_max=np.full((2, 8), 500.0, dtype=np.float32),
    )


def _read_csv_rows(path: pathlib.Path) -> list[list[str]]:
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.reader(fh))


def _make_meta(scan_id: str = "golden_normal") -> ScanMetadata:
    return ScanMetadata(
        scan_id=scan_id,
        subject_id="x",
        operator="x",
        started_at_iso="2026-05-22T00:00:00Z",
        duration_sec=10,
        left_camera_mask=0x01,
        right_camera_mask=0,
        reduced_mode=False,
    )


def _run_replay(raw_csv_path: pathlib.Path, output_dir: pathlib.Path,
                meta: ScanMetadata) -> pathlib.Path:
    pipeline = default_pipeline(
        metadata=meta,
        calibration=_trivial_calibration(),
        pedestals=SensorPedestals(left=_PEDESTAL, right=_PEDESTAL),
        dark_interval=_DARK_INTERVAL,
    )
    source = CsvReplaySource(
        raw_csv_left=raw_csv_path,
        raw_csv_right=None,
        batch_size_frames=20,
        metadata=meta,
    )
    sink = CsvSink(output_dir=str(output_dir))
    ScanRunner(source=source, pipeline=pipeline, sinks=[sink]).run()

    corrected_files = list(output_dir.glob("*corrected*.csv"))
    if not corrected_files:
        pytest.fail(
            "No corrected CSV produced — CsvSink.consume('final') is still a no-op "
            "or no dark interval closed during replay."
        )
    return corrected_files[0]


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_normal_short_scan_matches_golden(tmp_path: pathlib.Path) -> None:
    """Replay the synthetic 50-frame scan and assert byte-identical output."""
    raw_csv = HERE / "normal_short_scan.raw.csv"
    golden  = HERE / "normal_short_scan.corrected.golden.csv"

    if not raw_csv.exists():
        pytest.skip("Raw fixture not found — run regenerate_goldens.py")
    if not golden.exists():
        pytest.skip("Golden not found — run regenerate_goldens.py")

    meta = _make_meta("golden_normal")
    actual_path = _run_replay(raw_csv, tmp_path, meta)

    actual_rows = _read_csv_rows(actual_path)
    golden_rows = _read_csv_rows(golden)

    assert actual_rows == golden_rows, (
        f"Pipeline output differs from golden.\n"
        f"Actual rows: {len(actual_rows)}, Golden rows: {len(golden_rows)}\n"
        f"First differing row index: "
        + str(next(
            (i for i, (a, g) in enumerate(zip(actual_rows, golden_rows)) if a != g),
            "lengths differ",
        ))
    )


def test_corrected_csv_has_expected_header(tmp_path: pathlib.Path) -> None:
    """Corrected CSV must start with the 82-column legacy header."""
    raw_csv = HERE / "normal_short_scan.raw.csv"
    if not raw_csv.exists():
        pytest.skip("Raw fixture not found — run regenerate_goldens.py")

    meta = _make_meta("header_check")
    actual_path = _run_replay(raw_csv, tmp_path, meta)
    rows = _read_csv_rows(actual_path)

    assert rows[0] == _NORMAL_HEADERS, (
        f"Header mismatch. Got: {rows[0][:5]}..."
    )


def test_corrected_csv_has_data_rows(tmp_path: pathlib.Path) -> None:
    """At least one corrected frame must be present (interval must close)."""
    raw_csv = HERE / "normal_short_scan.raw.csv"
    if not raw_csv.exists():
        pytest.skip("Raw fixture not found — run regenerate_goldens.py")

    meta = _make_meta("data_rows_check")
    actual_path = _run_replay(raw_csv, tmp_path, meta)
    rows = _read_csv_rows(actual_path)

    assert len(rows) > 1, "Corrected CSV has no data rows — no interval closed."
